FROM jenkins/jenkins:lts

USER root

# Installation des dépendances, d'Ansible et des plugins Jenkins
RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    sshpass \
    && pip3 install ansible \
    && jenkins-plugin-cli --plugins \
    git \
    git-client \
    github \
    github-branch-source \
    ansible \
    pipeline-stage-view \
    blueocean \
    && rm -rf /var/lib/apt/lists/*

# Retour à l'utilisateur jenkins
USER jenkins
